{
 "title": "SLO draft",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "query_result(sum(istio_requests_total{}) by (destination_service) or sum(istio_tcp_sent_bytes_total{}) by (destination_service))"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "# SLI's / SLO's\n\nSee: [The Art of SLOs](https://cre.page.link/art-of-slos-slides)"
   }
  },
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "options": {
    "content": "<div style=\"background-color: #ffe082; color: #000; padding: 10px; border-radius: 8px;\">\n  <h2>Availability</h2>\n  <ul>\n    <li><b>SLI:</b> The percentage of successful requests served by the service over a 24-hour period</li>\n    <li><b>SLO:</b> At least 96% of requests must be successful over a 24-hour period</li>\n    <li><b>Error budget:</b> 4% of requests that are allowed to fail within a 24-hour period, given a 96% SLO</li>\n  </ul>\n</div>"
   }
  },
  {
   "title": "Success rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(\n  sum(irate(istio_requests_total{destination_service=~\"${service}\",response_code!~\"5.*\"}[1m]))\n  /\n  sum(irate(istio_requests_total{destination_service=~\"${service}\"}[1m]))\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total reqs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(istio_requests_total{destination_service=~\"${service}\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cumulative SLO (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "(\n  sum(increase(istio_requests_total{destination_service=~\"${service}\", response_code!~\"5.*\"}[1d]))\n  /\n  sum(increase(istio_requests_total{destination_service=~\"${service}\"}[1d]))\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error budget (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "(\n  sum(increase(istio_requests_total{destination_service=~\"${service}\", response_code=~\"5.*\"}[1d]))\n  /\n  sum(increase(istio_requests_total{destination_service=~\"${service}\"}[1d]))\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Burn rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "(\n  sum(increase(istio_requests_total{destination_service=~\"${service}\", response_code=~\"5.*\"}[1d]))\n  /\n  sum(increase(istio_requests_total{destination_service=~\"${service}\"}[1d]))\n) / 0.04",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error budget (%) - max_over_time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(\n  (\n    sum(increase(istio_requests_total{destination_service=~\"${service}\", response_code=~\"5.*\"}[24h]))\n    /\n    sum(increase(istio_requests_total{destination_service=~\"${service}\"}[24h])\n  ) * 100\n)[24h:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true
  },
  {
   "title": "Saturation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true
  }
 ]
}