{
 "title": "SLO draft",
 "tags": [
  "prometheus",
  "istio",
  "sre"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "query_result(sum(istio_requests_total{}) by (destination_service) or sum(istio_tcp_sent_bytes_total{}) by (destination_service))"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "# SLI's / SLO's\n\nSee: [The Art of SLOs](https://cre.page.link/art-of-slos-slides)"
   }
  },
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "options": {
    "content": "<div style=\"background-color: #ffe082; color: #000; padding: 10px; border-radius: 8px;\">\n  <h2>Availability</h2>\n  <ul>\n    <li><b>SLI:</b> The percentage of successful requests served by the service over a <b>24-hour</b> period.</li>\n    <li><b>SLO:</b> At least 99% of requests must be successful over a <b>24-hour</b> period.</li>\n    <li><b>Error budget:</b> 1% of requests that are allowed to fail within a <b>24-hour</b> period, given a 99% SLO.</li>\n  </ul>\n</div>"
   }
  },
  {
   "title": "Total reqs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(istio_requests_total{destination_service=~\"${service}\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Success Reqs (non-5xx responses)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(istio_requests_total{destination_service=~\"${service}\", response_code!~\"5.*\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Failure Reqs (5xx responses)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(istio_requests_total{destination_service=~\"${service}\", response_code=~\"5.*\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success rate (%) [1m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "(\n  sum(irate(istio_requests_total{destination_service=~\"${service}\",response_code!~\"5.*\"}[1m]))\n  /\n  sum(irate(istio_requests_total{destination_service=~\"${service}\"}[1m]))\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cumulative SLO (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "(\n  sum(increase(istio_requests_total{destination_service=~\"${service}\", response_code!~\"5.*\"}[$__range]))\n  /\n  sum(increase(istio_requests_total{destination_service=~\"${service}\"}[$__range]))\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error budget (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "(\n  sum(increase(istio_requests_total{destination_service=~\"${service}\", response_code=~\"5.*\"}[$__range]))\n  /\n  sum(increase(istio_requests_total{destination_service=~\"${service}\"}[$__range]))\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Burn rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "(\n  sum(increase(istio_requests_total{destination_service=~\"${service}\", response_code=~\"5.*\"}[$__range]))\n  /\n  sum(increase(istio_requests_total{destination_service=~\"${service}\"}[$__range]))\n) / 0.04",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error budget (%) - max_over_time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(\n  (\n    sum(increase(istio_requests_total{destination_service=~\"${service}\", response_code=~\"5.*\"}[$__range]))\n    /\n    sum(increase(istio_requests_total{destination_service=~\"${service}\"}[$__range])\n  ) * 100\n)[24h:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 44 },
   "options": {
    "content": "<div style=\"background-color: #ffe082; color: #000; padding: 10px; border-radius: 8px;\">\n  <h2>Latency</h2>\n  <ul>\n    <li><b>SLI:</b> The percentage of successful HTTP GET requests with latency below <b>25ms</b> over a <b>24-hour</b> period.</li>\n    <li><b>SLO:</b> At least <b>99%</b> of successful HTTP GET requests must have latency below <b>25ms</b> over a <b>24-hour</b> period.</li>\n    <li><b>Error budget:</b> Up to <b>1%</b> of successful HTTP GET requests are allowed to exceed <b>25ms</b> latency within a <b>24-hour</b> period, given a 99% SLO.</li>\n  </ul>\n</div>"
   }
  },
  {
   "title": "p99",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (\n    rate(istio_request_duration_milliseconds_bucket{response_code=~\"2..\", destination_service=\"${service}\"}[$__range])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p90",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le) (\n    rate(istio_request_duration_milliseconds_bucket{response_code=~\"2..\", destination_service=\"${service}\"}[$__range])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p85",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.85,\n  sum by (le) (\n    rate(istio_request_duration_milliseconds_bucket{response_code=~\"2..\", destination_service=\"${service}\"}[$__range])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p50",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le) (\n    rate(istio_request_duration_milliseconds_bucket{response_code=~\"2..\", destination_service=\"${service}\"}[$__range])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true
  }
 ]
}