apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  enableOCI: "true"
  type: helm
  url: registry-1.docker.io
  project: lab-apps-canary
