apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-ms-13-shadow
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: https://kubernetes.default.svc
  template:
    metadata:
      name: demo-ms-13-shadow
    spec:
      project: "lab-apps-shadow"
      source:
        repoURL: 'registry-1.docker.io/paulofponciano'
        chart: demo-ms-intercomunicacao
        targetRevision: 0.1.19
        helm:
          releaseName: demo-ms-13-shadow
          valuesObject:
            name: demo-ms-13-shadow
            namespace: demo
            image: paulofponciano/demo-ms-intercomunicacao:latest
            replicas: 1
            env:
              - name: TITLE
                value: "Microservice 13 Shadow"
              - name: RESPONSE_TIME
                value: "0"
              - name: EXTERNAL_CALL_URL
                value: ""
              - name: EXTERNAL_CALL_METHOD
                value: "GET"
              - name: APP_VERSION
                value: "0.1.6"
            service:
              portName: http
              port: 5000
              protocol: TCP
              targetPort: 5000
            istio:
              virtualService:
                enabled: true
                protocol: http
                retries:
                  attempts: 2
                  perTryTimeout: 500ms
                  retryOn: connect-failure,refused-stream,unavailable,cancelled,503
              gateway:
                enabled: false
                name: demo-ms-13-shadow-gateway
                host: demo-ms-intercomunicacao.sevira.cloud
                selector: ingressgateway
            prometheus:
                scrape: false
                path: /metrics
                port: 5000
            livenessProbe:
              enabled: true
              path: /healthz
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 5
            readinessProbe:
              enabled: true
              path: /ready
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 5
            strategy:
              type: canary
              canary:
                steps:
                - setWeight: 100
      destination:
        server: '{{ cluster }}'
        namespace: argocd
      syncPolicy:
        automated: {}
