name: demo-ms-intercomunicacao
namespace: demo
image: paulofponciano/demo-ms-intercomunicacao:latest
replicas: 1

env:
  - name: TITLE
    value: "Microservice 1"
  - name: RESPONSE_TIME
    value: "500"
  - name: EXTERNAL_CALL_URL
    value: ""
  - name: EXTERNAL_CALL_METHOD
    value: "GET"

service:
  portName: http
  port: 5000
  protocol: TCP
  targetPort: 5000

istio:
  virtualService:
    enabled: true
    protocol: tcp
    retries:
      attempts: 2
      perTryTimeout: 500ms
      retryOn: connect-failure,refused-stream,unavailable,cancelled,503
  gateway:
    enabled: false
    name: demo-ms-1-gateway
    host: demo-ms-intercomunicacao.sevira.cloud
    selector: ingressgateway

strategy:
  canary:
    steps:
      - setWeight: 0
      - pause: {}
      - setWeight: 10
      - pause: {}
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {}
      - setWeight: 80
      - pause: {}
      - setWeight: 100

prometheus:
  scrape: true
  path: /metrics
  port: 5000
