---
apiVersion: v1
kind: Service
metadata:
  name: microservice-3
  namespace: sample-api-python
spec:
  selector:
    app: microservice-3
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
