apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: microservice-1
  namespace: sample-api-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-1
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-python: "o11y/python-auto-instrumentation"
      labels:
        app: microservice-1
    spec:
      containers:
      - name: app
        image: paulofponciano/demo-ms-intercomunicacao:latest
        ports:
        - containerPort: 5000
        env:
        - name: TITLE
          value: "Microservice 1"
        - name: RESPONSE_TIME
          value: "500"
        - name: EXTERNAL_CALL_URL
          value: "http://microservice-2.sample-api-python.svc.cluster.local:5000"
        - name: EXTERNAL_CALL_METHOD
          value: "GET"
  strategy:
    canary:
      steps:
      - setWeight: 0
      - pause: { }
      - setWeight: 10
      - pause: { }
      - setWeight: 20
      - pause: { }
      - setWeight: 40
      - pause: { }
      - setWeight: 80
      - pause: { }
      - setWeight: 100
