{{- if .Values.istio.virtualService.enabled }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    {{- if .Values.istio.gateway.enabled }}
    - {{ .Values.istio.gateway.host }}
    {{- else }}
    - {{ printf "%s.%s.svc.cluster.local" .Values.name .Values.namespace }}
    {{- end }}
  gateways:
    {{- if .Values.istio.gateway.enabled }}
    - {{ .Values.istio.gateway.name }}
    {{- else }}
    - mesh
    {{- end }}
  {{- if eq (upper .Values.istio.virtualService.protocol) "HTTP" }}
  http:
    - route:
        - destination:
            host: {{ printf "%s.%s.svc.cluster.local" .Values.name .Values.namespace }}
            port:
              number: {{ .Values.service.port | default 5000 }}
      retries:
        attempts: {{ .Values.istio.virtualService.retries.attempts }}
        perTryTimeout: {{ .Values.istio.virtualService.retries.perTryTimeout }}
        retryOn: {{ .Values.istio.virtualService.retries.retryOn }}
  {{- else if eq (upper .Values.istio.virtualService.protocol) "TCP" }}
  tcp:
    - match:
        - port: {{ .Values.service.port | default 5000 }}
      route:
        - destination:
            host: {{ printf "%s.%s.svc.cluster.local" .Values.name .Values.namespace }}
            port:
              number: {{ .Values.service.port | default 5000 }}
  {{- end }}
{{- end }}